apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0ff6ea82c647b700b
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  storageClassName: ""
  volumeName: efs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1 
kind: pod 
metadata:
  name: nginx-pod
spec:
  containers:
  - image: nginx
    name: nginx
    labels:
      type: nginx-pod
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
       claimName: my-pvc
---
apiVersion: v1 
kind: service 
metadata:
  name: nginx-service
spec:
    type: LoadBalancer
    selector:
      purpose: efs-static
    ports:
    - protocol: TCP
      port: 80 #service-port
      targetPort: 80


