kind: PersistentVolumeClaim
apiVersion: v1 
metadata:
   name: efs-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-dynamic
  resources:
   requests:
    storage: 5Gi
---
kind: Pod 
apiVersion: v1 
metadata:
   name: nginx-dynamic-pod
   labels:
     type: dynamic-nginx
spec:
  containers:
   - name: nginx
     image: nginx
     volumeMounts:
       - name: persistent-storage
         mountPath: /usr/share/nginx/html
  volumes:
   - name: nginx-dynamic
     persistentVolumeClaim: 
       claimName: efs-dynamic
---
apiVersion: v1 
kind: Service 
metadata: 
  name: nginx-dynamic
spec:
  type: LoadBalancer
  selector:
   type: dynamic-nginx
  ports:
  -  protocol: TCP
     port: 80
     targetPort: 80

