kind: Pod
apiVersion: v1 
metadata:
  name: annotations
  labels:
   course: kubernetes
   trainer: joindevops
  annotations:
    kubernetes.io/created-by: 'sivakumar'
    jenkins.build.url: 'https://jenkins.daws78s.online/expense/job/backend/54'
spec:
 containers:
 - name: nginx
   image: nginx