kind: Pod
apiVersion: v1
metadata:
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapRef:
        name: kubernetes
    # env:
    # - name:  course
    #   valueFrom:
    #         configMapKeyRef:
    #           name: kubernetes           # The ConfigMap this value comes from.
    #           key: course # The key to fetch. 
    # - name:  trainer
    #   valueFrom:
    #         configMapKeyRef:
    #           name: kubernetes
    #           key: trainer

    #envFrom is used to directly use all the key values from the configmap file