kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  selector:
    name: nginx
    environment: dev
    project: expense
    component: frontend
  ports:
   - protocol: TCP
     port: 80
     targetport: 80

