apiVersion: v1
kind: Service
metadata: 
  name: nginx-np
spec:
  type: NodePort
  selector:
          name: nginx
          environment: dev
          project: expense
          component: frontend
  ports:
    - protocol: TCP
      port: 80 #service-port
      targetPort: 80 #target-port
      NodePort: 32760



