apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica
  #these labels belong to replicaset resource
  labels:
    app: nginx
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  #below is pod definition
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
        project: expense
    spec:
      containers:
      - name: nginx
        image: nginx:stable-perl
