apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: frontend
      
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
        project: expense
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          
