apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-basic-cluster
  region: us-east-1

managedNodeGroups:
- name: expense
  instanceType: t2.medium
  desiredCapacity: 2
  spot: true